/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.appuntivari.mylibrary.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the MyLibrary service. Represents a row in the &quot;AV_MyLibrary&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.appuntivari.mylibrary.model.impl.MyLibraryModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.appuntivari.mylibrary.model.impl.MyLibraryImpl}.
 * </p>
 *
 * @author Pasturenzi Francesco
 * @see MyLibrary
 * @see com.appuntivari.mylibrary.model.impl.MyLibraryImpl
 * @see com.appuntivari.mylibrary.model.impl.MyLibraryModelImpl
 * @generated
 */
public interface MyLibraryModel extends BaseModel<MyLibrary> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a my library model instance should use the {@link MyLibrary} interface instead.
	 */

	/**
	 * Returns the primary key of this my library.
	 *
	 * @return the primary key of this my library
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this my library.
	 *
	 * @param primaryKey the primary key of this my library
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the id_book of this my library.
	 *
	 * @return the id_book of this my library
	 */
	public long getId_book();

	/**
	 * Sets the id_book of this my library.
	 *
	 * @param id_book the id_book of this my library
	 */
	public void setId_book(long id_book);

	/**
	 * Returns the titolo of this my library.
	 *
	 * @return the titolo of this my library
	 */
	@AutoEscape
	public String getTitolo();

	/**
	 * Sets the titolo of this my library.
	 *
	 * @param titolo the titolo of this my library
	 */
	public void setTitolo(String titolo);

	/**
	 * Returns the descrizione of this my library.
	 *
	 * @return the descrizione of this my library
	 */
	@AutoEscape
	public String getDescrizione();

	/**
	 * Sets the descrizione of this my library.
	 *
	 * @param descrizione the descrizione of this my library
	 */
	public void setDescrizione(String descrizione);

	/**
	 * Returns the autori of this my library.
	 *
	 * @return the autori of this my library
	 */
	@AutoEscape
	public String getAutori();

	/**
	 * Sets the autori of this my library.
	 *
	 * @param autori the autori of this my library
	 */
	public void setAutori(String autori);

	/**
	 * Returns the stato of this my library.
	 *
	 * @return the stato of this my library
	 */
	@AutoEscape
	public String getStato();

	/**
	 * Sets the stato of this my library.
	 *
	 * @param stato the stato of this my library
	 */
	public void setStato(String stato);

	/**
	 * Returns the link_more_info of this my library.
	 *
	 * @return the link_more_info of this my library
	 */
	@AutoEscape
	public String getLink_more_info();

	/**
	 * Sets the link_more_info of this my library.
	 *
	 * @param link_more_info the link_more_info of this my library
	 */
	public void setLink_more_info(String link_more_info);

	/**
	 * Returns the note of this my library.
	 *
	 * @return the note of this my library
	 */
	@AutoEscape
	public String getNote();

	/**
	 * Sets the note of this my library.
	 *
	 * @param note the note of this my library
	 */
	public void setNote(String note);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(MyLibrary myLibrary);

	public int hashCode();

	public CacheModel<MyLibrary> toCacheModel();

	public MyLibrary toEscapedModel();

	public MyLibrary toUnescapedModel();

	public String toString();

	public String toXmlString();
}